be/build.gradle, be/settings.gradle, be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/BeApplication.java, be/src/main/java/com/foodymoody/be/DocumentController.java, be/src/test/java/com/foodymoody/be/BeApplicationTests.java, be/src/test/java/com/foodymoody/be/docs/Document.java
=> [BE] 프로젝트 환경 세팅

fe/src/styles/designSystem.ts
=> chore: 디자인시스템 - 폰트 추가

fe/src/styles/mediaQuery.ts
=> [FE] chore: 미디어 쿼리 설정

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/auth/AuthController.java, be/src/main/java/com/foodymoody/be/common/RestDocsController.java, be/src/test/java/com/foodymoody/be/docs/Document.java, be/src/test/java/com/foodymoody/be/docs/auth/AuthSteps.java, be/src/test/java/com/foodymoody/be/docs/auth/AuthTest.java
- `@Container` 및 '@TestContainer' 제거 
- 있으면 Docker를 이미지를 중지한다.
=> Be/feat/14 be 인증 이미지 인수 테스트

fe/src/App.tsx, fe/src/styles/designSystem.ts, fe/src/types/theme.d.ts
=> [FE] 디자인시스템 - 타입선언

fe/src/components/common/icons.ts, fe/src/components/common/logo/Logo.tsx, fe/src/pages/test/TestPage.tsx
=> [FE] 로고 컴포넌트 구현

fe/.prettierrc, fe/package-lock.json, fe/package.json, fe/src/pages/test/TestPage.tsx
=> [FE] prettier import sort 세팅 추가 

be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java, be/src/main/java/com/foodymoody/be/feed/domain/Feed.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java, be/src/main/java/com/foodymoody/be/feed/service/FeedService.java, be/src/test/java/com/foodymoody/be/feed/FeedSteps.java, be/src/test/java/com/foodymoody/be/feed/FeedTest.java
=> [Be] Feed 전체 페이지 조회 슬라이싱 구현 후 테스트 코드 작성

fe/src/components/common/Button/Button.tsx, fe/src/styles/globalStyles.ts
- 
size, backgroundColor 필수. 글자색 안넣어도 됨
width 있으면 고정 없으면 100%
```js
// 예시 코드
<div style={{ width: '300px' }}>
<Button size="l" backgroundColor="black">
가입하기
</Button>
</div>
<div style={{ width: '200px' }}>
<Button size="l" backgroundColor="black">
가입하기
</Button>
</div>
<Button size="s" backgroundColor="white" width={100}>
가입하기
</Button>
<Button size="s" backgroundColor="orange" disabled>
<CollectableAddIcon></CollectableAddIcon>
가입하기
</Button>
```
=> [FE] Button 컴포넌트 구현

fe/src/components/common/Button/TextButton.tsx
- #46 
- 이전 버튼 컴포넌트 복붙해서 수정한거라 이상한거 있을 수도 있음 (?)
=> [FE] TextButton 컴포넌트 구현

fe/src/components/common/badge/Badge.tsx, fe/src/components/common/badgeSelector/BadgeSelector.tsx, fe/src/types/type.d.ts
=> [FE] BadgeSelector 컴포넌트 구현

fe/src/components/common/icons.ts, fe/src/components/common/starRating/StarRating.tsx
- #59 
- 별점 점수 0-5점을 onClick으로 뱉습니다
- 부모 쪽에서 점수 넣어줘야 함
```js
// 부모 컴포넌트
const [rating, setRating] = useState(0);
const hadleFn = (num) => {
setRating(num);
};
<StarRating onClick={hadleFn} rating={rating}></StarRating>
```
=> [FE] StarRating 컴포넌트 구현

fe/src/components/common/menuRateTag/MenuRateTag.tsx
=> [FE] MenuRateTag 컴포넌트 구현

be/build.gradle, be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java, be/src/main/java/com/foodymoody/be/comment/controller/RegisterCommentRequest.java, be/src/main/java/com/foodymoody/be/comment/domain/Comment.java, be/src/main/java/com/foodymoody/be/comment/domain/CommentValidator.java, be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java, be/src/main/java/com/foodymoody/be/comment/service/CommentService.java, be/src/main/java/com/foodymoody/be/comment/util/CommentMapper.java, be/src/main/java/com/foodymoody/be/comment/util/CommentValidator.java, be/src/main/java/com/foodymoody/be/common/RestDocsController.java, be/src/main/java/com/foodymoody/be/common/exception/BusinessException.java, be/src/main/java/com/foodymoody/be/common/exception/ContentIsEmptyException.java, be/src/main/java/com/foodymoody/be/common/exception/ContentIsOver200Exception.java, be/src/main/java/com/foodymoody/be/common/exception/ContentIsSpaceException.java, be/src/main/java/com/foodymoody/be/common/exception/ContentNotExistsException.java, be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java, be/src/main/java/com/foodymoody/be/common/exception/ErrorResponse.java, be/src/main/java/com/foodymoody/be/common/exception/FeedIdNotExistsException.java, be/src/main/java/com/foodymoody/be/common/exception/GlobalExceptionHandler.java, be/src/main/java/com/foodymoody/be/common/exception/InvalidIdException.java, be/src/main/java/com/foodymoody/be/common/exception/RegisterCommentRequestNotNullException.java, be/src/main/java/com/foodymoody/be/common/util/Constants.java, be/src/main/java/com/foodymoody/be/common/util/IdGenerator.java, be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java, be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java, be/src/test/java/com/foodymoody/be/comment/util/CommentValidatorTest.java
=> Be/feat/#66 be 인증로직 리펙토링

fe/src/components/common/userFeedTabs/UserFeedTabs.tsx
- 
```
// 부모.tsx
export const HomePage = () => {
const [index, setIndex] = useState(0);
const handleFeedTab = (index: number) => {
setIndex(index);
};
return (
<div>
Home
<UserFeedTabs index={index} onClick={handleFeedTab} />
</div>
);
};
```
=> [FE] UserFeedTabs구현

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/feed/domain/Feed.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java, be/src/main/java/com/foodymoody/be/feed/service/FeedService.java, be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java, be/src/test/java/com/foodymoody/be/feed/FeedSteps.java, be/src/test/java/com/foodymoody/be/feed/FeedTest.java
=> [BE] Feed 로직에 createdAt과 updatedAt 추가 후 테스트

fe/index.html, fe/src/App.tsx, fe/src/components/common/modal/Modal.tsx
- #71 
- Modal 설명 첨부 https://www.notion.so/Modal-a9b854ec1c0b476ca403bf30d4eddb6d
- recoil 관련 오류 설명 첨부 https://www.notion.so/Recoil-Duplicate-atom-key-2b4b4f959bd7497880a34340b2d85331
- `.env` 파일 만들어줘야해요
=> [FE] Modal 관리 로직 구현

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java, be/src/main/java/com/foodymoody/be/comment/domain/Comment.java, be/src/main/java/com/foodymoody/be/comment/domain/CommentId.java, be/src/main/java/com/foodymoody/be/comment/domain/CommentValidator.java, be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java, be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java, be/src/main/java/com/foodymoody/be/comment/service/CommentService.java, be/src/main/java/com/foodymoody/be/common/exception/BusinessException.java, be/src/main/java/com/foodymoody/be/common/exception/CommentDeletedException.java, be/src/main/java/com/foodymoody/be/common/exception/CommentNotExistsException.java, be/src/main/java/com/foodymoody/be/common/exception/ContentIsEmptyException.java, be/src/main/java/com/foodymoody/be/common/exception/ContentIsOver200Exception.java, be/src/main/java/com/foodymoody/be/common/exception/ContentIsSpaceException.java, be/src/main/java/com/foodymoody/be/common/exception/ContentNotExistsException.java, be/src/main/java/com/foodymoody/be/common/exception/CreateTimeIsNullException.java, be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java, be/src/main/java/com/foodymoody/be/common/exception/FeedIdNotExistsException.java, be/src/main/java/com/foodymoody/be/common/exception/InvalidIdException.java, be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java, be/src/test/java/com/foodymoody/be/acceptance/comment/CommentTest.java, be/src/test/java/com/foodymoody/be/comment/domain/CommentTest.java, be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java, be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java, be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
- Spring 의 핵심 DI를 적용하기 위해서 모든 static 클래스를 주입하는 형식으로 변경하면 좋을 것 같아요.
- 필드 타입을 모두 객체를 만드는것도 좋은 방법일수도 있을 것 같아요. 
-  Comment의 id를 CommentId 로 감싸서 타입 안정서을 가질수 있다.
close #94
=> Be/feat/#94 be 댓글 삭제

be/build.gradle
- /api/docs경로의 페이지가 보여지지 않는 오류를 해결했습니다
- 시간이 늦어 리뷰어 지정은 코어타임에 하겠습니다
=> fix: /api/docs 작동 안하는 오류 수정

fe/src/components/common/headerMob/HeaderMob.tsx, fe/src/components/common/notiIcon/NotiIcon.tsx, fe/src/components/common/userFeedTabs/UserFeedTabs.tsx, fe/src/components/common/userImage/UserImageEdit.tsx, fe/src/components/profileUserInfo/ProfileUserInfo.tsx, fe/src/pages/Layout.tsx, fe/src/pages/LoginPage.tsx, fe/src/pages/ProfilePage.tsx, fe/src/pages/RegisterPage.tsx, fe/src/types/type.d.ts
=> [FE] 프로필 페이지UI

fe/src/components/common/commentItem/CommentItem.tsx
- 
- 이전 pr들이 아직 합쳐지지 않아 fetcher들이 합쳐지고 난 이후 진행해도 될 것 같습니다
=> [FE]  commentitem 컴포넌트 UI 

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/comment/controller/FeedCommentController.java, be/src/main/java/com/foodymoody/be/comment/controller/dto/CommentResponse.java, be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java, be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java, be/src/main/java/com/foodymoody/be/comment/service/CommentService.java, be/src/main/java/com/foodymoody/be/comment/service/FeedCommentService.java, be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java, be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java, be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java, be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java, be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java, be/src/test/resources/application-db.yml
=> [BE] 피브별 댓글 조회

be/src/main/java/com/foodymoody/be/feed/domain/Feed.java, be/src/main/java/com/foodymoody/be/feed/domain/ImageMenu.java, be/src/main/java/com/foodymoody/be/feed/domain/ImageMenus.java, be/src/main/java/com/foodymoody/be/feed/domain/StoreMood.java, be/src/main/java/com/foodymoody/be/feed/domain/util/ImageMenuMapper.java, be/src/main/java/com/foodymoody/be/feed/service/FeedService.java, be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java, be/src/main/java/com/foodymoody/be/mood/domain/Mood.java
- ImageMenus로 관리합니다.
- Mood Entity는 추가만 해두었습니다.
-
=> [BE] Images, Menus 관계 수정

be/src/main/java/com/foodymoody/be/feed/domain/Feed.java, be/src/main/java/com/foodymoody/be/feed/domain/StoreMood.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java, be/src/main/java/com/foodymoody/be/feed/service/FeedService.java, be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java, be/src/main/java/com/foodymoody/be/mood/repository/MoodRepository.java, be/src/test/resources/application-db.yml, be/src/test/resources/data.sql
=> [BE] Mood DB 적용

be/src/main/java/com/foodymoody/be/feed/domain/Feed.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java, be/src/main/java/com/foodymoody/be/feed/dto/response/FeedStoreMoodResponse.java, be/src/main/java/com/foodymoody/be/feed/service/FeedService.java, be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java, be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
=> [BE] Mood Response 수정 완료

fe/src/components/common/carousel/Carousel.tsx, fe/src/components/common/dim/Dim.tsx, fe/src/components/common/feedAction/FeedAction.tsx, fe/src/components/common/headerMob/HeaderMob.tsx, fe/src/components/common/input/Input.tsx, fe/src/components/common/input/InputCore.tsx, fe/src/components/common/navibar/NaviBar.tsx, fe/src/components/common/textarea/Textarea.tsx, fe/src/components/feedMain/FeedMainItem.tsx, fe/src/hooks/useLockBodyScroll.ts, fe/src/pages/DetailFeedPage.tsx, fe/src/pages/HomePage.tsx, fe/src/pages/Layout.tsx, fe/src/pages/NewFeedPage.tsx, fe/src/pages/ProfilePage.tsx, fe/src/routes/router.tsx, fe/src/styles/customScrollStyle.ts, fe/src/types/feed.d.ts
- react router background 
- add custom scroll style
- add useLockBodyScroll
- (의견) FeedAction에 CommentIcon 클릭 핸들러 위로 올려줬는데, 나중에 하트 클릭도 위로 올려서 처리 하는 게 좋을 것 같음. 그 Action바를 나중에 컬렉션에서도 재활용할 수 있지 않을까? 싶습니다
- useLockBodyScroll 사용법
```js
useLockBodyScroll(true);
useLockBodyScroll(isLock);
```
- Dim 컴포넌트
- 다른 곳에서도 쓸 수 있을 것 같아서 Dim을 클릭 한 후 무슨 일이 일어날지는 위에서 넣어주게 만들었어요.
```js
type Props = {
onClick: () => void;
};
export const Dim: React.FC<Props> = ({ onClick }) => {
useLockBodyScroll(true);
return (
<Wrapper onClick={onClick}>
<CloseBtn />
</Wrapper>
);
};
```
closed #110
=> [FE] DeatilModalPage 구현

fe/package-lock.json, fe/package.json, fe/src/api/fetcher.ts, fe/src/assets/face.svg, fe/src/assets/userPlus.svg, fe/src/components/common/Button/TextButton.tsx, fe/src/components/common/commentItem/CommentItem.tsx, fe/src/components/common/dropdown/Dropdown.tsx, fe/src/components/common/icon/icons.ts, fe/src/components/common/input/CommentInput.tsx, fe/src/components/common/input/Input.tsx, fe/src/components/common/navibar/NaviBar.tsx, fe/src/components/profileUserInfo/ProfileUserInfo.tsx, fe/src/hooks/useMenuItem.ts, fe/src/pages/DetailFeedPage.tsx, fe/src/pages/NewFeedPage.tsx, fe/src/queries/auth.ts, fe/src/utils/localStorage.ts, fe/vite.config.ts
- uuid 라이브러리 삭제 -> crypto api로 변경
- emoji-picker-react 추가
- comment Item 답글 달기 버튼 추가
- 기타 200자 제한 등 valid조건 추가
-
=> [FE] comment 제한 사항 보완

be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java, be/src/main/java/com/foodymoody/be/comment/domain/Comment.java, be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java, be/src/main/java/com/foodymoody/be/comment/service/CommentService.java, be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java, be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java, be/src/test/java/com/foodymoody/be/comment/domain/CommentTest.java, be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java, be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java, be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java, be/src/test/resources/application-auth.yml
- 테스트가 Sully 의 Feed 등록와 연동 되여 있어서 Feed 등록 수정시 함께 해주셔도 좋고 알려주셔도 좋습니다.
=> [BE] 댓글 리펙토링

be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
=> docs: RestDocs 수정

fe/package-lock.json, fe/src/App.tsx, fe/src/assets/toastError.svg, fe/src/assets/toastNoti.svg, fe/src/assets/toastSuccess.svg, fe/src/components/common/icon/icons.ts, fe/src/components/common/toast/Toast.tsx, fe/src/recoil/toast/atom.ts, fe/src/recoil/toast/useToast.ts, fe/src/types/toast.d.ts
- 
- 사용법
```js
export const HomePage = () => {
const toast = useToast();
const handleSuccess = () => {
toast.success('성공이에용ddasadsaasdafsdasfaasdafsdsdadd');
};
const handleError = () => {
toast.error('에러에용');
};
const handleNoti = () => {
toast.noti('알림이에용');
};
return (
<Wrapper>
<button onClick={handleSuccess}>성공 버튼</button>
<button onClick={handleError}>에러 버튼</button>
<button onClick={handleNoti}>노티 버튼</button>
</Wrapper>
);
};
```
=> [FE] Toast 구현

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java, be/src/main/java/com/foodymoody/be/comment/controller/FeedCommentController.java, be/src/main/java/com/foodymoody/be/comment/controller/dto/MemberResponse.java, be/src/main/java/com/foodymoody/be/comment/controller/dto/RegisterReplyRequest.java, be/src/main/java/com/foodymoody/be/comment/controller/dto/ReplyResponse.java, be/src/main/java/com/foodymoody/be/comment/domain/Comment.java, be/src/main/java/com/foodymoody/be/comment/domain/Reply.java, be/src/main/java/com/foodymoody/be/comment/domain/ReplyComments.java, be/src/main/java/com/foodymoody/be/comment/domain/ReplyId.java, be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java, be/src/main/java/com/foodymoody/be/comment/repository/ReplyRepository.java, be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java, be/src/main/java/com/foodymoody/be/comment/service/CommentService.java, be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java, be/src/test/resources/application-filter.yml
=> [BE] 대댓글 리펙토링

fe/src/components/common/commentItem/CommentBox.tsx, fe/src/components/common/input/CommentInput.tsx, fe/src/service/queries/mood.ts, fe/src/service/queries/profile.ts, fe/tsconfig.json
-  textbutton import문 절대경로로 변경
-  절대경로로 에러 해결시 textbutton import 전부 절대경로로 변경 예정
-
=> [FE] 빌드 오류 수정중

fe/src/components/common/commentItem/CommentBox.tsx, fe/src/components/common/input/CommentInput.tsx, fe/src/service/queries/mood.ts, fe/src/service/queries/profile.ts, fe/tsconfig.json
=> [FE] dev-fe -> dev 

fe/src/components/feedMain/FeedMainItem.tsx, fe/src/pages/HomePage.tsx, fe/src/service/queries/feed.ts, fe/tsconfig.json
=> [FE] 메인 피드 데이터 연동 및 무한 스크롤 추가

fe/src/components/common/carousel/Carousel.tsx, fe/src/components/feedMain/FeedMainItem.tsx, fe/src/hooks/useReadMore.ts
- 
- 글이 다 짧은 거 밖에 없어서 테스트를 많이 못해봐서 오류 또 있을 수도 있음. 있으면 알려주세요
- 최대 글자 수는 임의로 그냥 해놨는데 나중에 같이 정해요
=> [FE] 더보기 버튼 오류 수정

fe/src/components/common/commentItem/CommentBox.tsx, fe/src/components/common/commentItem/CommentItem.tsx, fe/src/components/common/feedUserInfo/FeedUserInfo.tsx, fe/src/components/common/input/Input.tsx, fe/src/components/common/modal/Modal.tsx, fe/src/components/feedMain/FeedMainItem.tsx, fe/src/components/register/Register.tsx, fe/src/constants/path.ts, fe/src/hooks/useMenuItem.ts, fe/src/pages/DetailFeedPage.tsx, fe/src/pages/NewFeedPage.tsx, fe/src/recoil/toast/useToast.ts, fe/src/service/axios/auth/comment/reply.ts, fe/src/service/constants/endpoint.ts, fe/src/service/constants/queryKey.ts, fe/src/service/queries/comment.ts, fe/src/service/queries/reply.ts, fe/src/types/auth.d.ts, fe/src/types/comment.d.ts, fe/tsconfig.json
- alert연결 했습니다 
- 기능 확인을 위해 commentAlert 컴포넌트는 버튼-s-black 으로만 구성했습니다 디자인은 추후에 변경예정
-
=> [FE] alert 연결

fe/src/components/profileUserInfo/ProfileUserInfo.tsx, fe/src/pages/ProfilePage.tsx, fe/src/service/queries/profile.ts, fe/src/types/profile.d.ts
=> [FE] 프로필 페이지 프로필 영역 연동

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java, be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceDeleteRequest.java, be/src/main/java/com/foodymoody/be/feed/service/FeedService.java, be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
=> [BE] 피드 Member 권한 수정

fe/src/pages/NewFeedPage.tsx, fe/src/routes/router.tsx, fe/src/service/queries/feed.ts, fe/src/types/error.d.ts
=> [FE] 피드 오류 수정 및 라우터 수정

fe/src/pages/NewFeedPage.tsx, fe/src/routes/router.tsx, fe/src/service/queries/feed.ts, fe/src/types/error.d.ts
* fix: 글 작성/수정 페이지 ProtectedRoute 오류 수정
* fix: 오류 타입 수정 및 메서드 수정
- 
-
=> dev-fe -> dev 

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/feed/domain/Feed.java, be/src/main/java/com/foodymoody/be/feed/service/FeedService.java, be/src/main/java/com/foodymoody/be/heart/controller/HeartController.java, be/src/main/java/com/foodymoody/be/heart/dto/response/HeartResponse.java, be/src/main/java/com/foodymoody/be/heart/service/HeartService.java, be/src/main/java/com/foodymoody/be/heart/util/HeartMapper.java, be/src/main/java/com/foodymoody/be/member/domain/Member.java, be/src/test/java/com/foodymoody/be/acceptance/heart/HeartAcceptanceTest.java, be/src/test/java/com/foodymoody/be/acceptance/heart/HeartSteps.java
- 동시성 문제 해결은 일단 기능 구현 후에 리팩토링하면서 추가하려 합니다.
=> [BE] 좋아요 등록, 취소 기능 구현 후 피드에 적용

fe/package-lock.json, fe/package.json, fe/src/components/common/skeleton/DeferredComponent.tsx, fe/src/components/common/skeleton/FeedSkeleton.tsx, fe/src/components/feedMain/FeedMainList.tsx, fe/src/pages/HomePage.tsx, fe/src/service/queries/feed.ts, fe/src/styles/designSystem.ts
=> [FE] 메인 피드 로딩 스켈레톤 추가

be/src/main/java/com/foodymoody/be/common/util/BaseId.java
=> [BE] id Column 추가

be/src/docs/asciidoc/index.adoc
=> docs: RestDocs 오타 수정

be/src/main/java/com/foodymoody/be/reply_heart/presentation/ReplyHeartWriteController.java, be/src/test/java/com/foodymoody/be/acceptance/reply_heart/ReplyHeartSteps.java
=> [BE] 대댓글 API 누락

be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
=> 상세 페이지 좋아요 조회 문제 해결 후 배포

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
=> [BE] RestDocs 및 오타 수정

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/comment/infra/persistence/jpa/ReplyJpaRepository.java, be/src/main/java/com/foodymoody/be/notification/presentation/NotificationReadController.java, be/src/main/java/com/foodymoody/be/reply_heart/application/ReplyHeartWriteService.java, be/src/main/java/com/foodymoody/be/reply_heart/domain/ReplyHeart.java, be/src/main/java/com/foodymoody/be/reply_heart/domain/ReplyHeartRepository.java, be/src/main/java/com/foodymoody/be/reply_heart/infra/persistence/ReplyHeartRepositoryImpl.java, be/src/main/java/com/foodymoody/be/reply_heart/infra/persistence/jpa/ReplyHeartJpaRepository.java, be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartWriteUseCase.java, be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationSteps.java
=> [BE] 댓글 및 대댓글 좋아요 오류 수정

fe/src/components/common/skeleton/NotiSkeleton.tsx, fe/src/components/notification/NotiItem.tsx, fe/src/components/notification/NotiList.tsx, fe/src/pages/NotiPage.tsx, fe/src/service/axios/notifications/notifications.ts, fe/src/service/constants/endpoint.ts, fe/src/service/constants/queryKey.ts, fe/src/service/queries/feed.ts, fe/src/service/queries/notification.ts, fe/src/types/notification.d.ts
- 알림 페이지 데이터 받아오기
- 클릭했을 때 이동 관련은 아직 추가 안되어있음
- 크게 없음
=> [FE] 알림 페이지 UI 및 데이터 연동

be/src/docs/asciidoc/index.adoc, be/src/main/java/com/foodymoody/be/common/util/Content.java, be/src/main/java/com/foodymoody/be/common/util/IdResponse.java, be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/application/FeedCollectionCommentMapper.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/application/FeedCollectionCommentReadService.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/application/FeedCollectionCommentWriteService.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/domain/FeedCollectionComment.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/domain/FeedCollectionCommentRepository.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/infra/persistence/FeedCollectionCommentRepositoryImpl.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/infra/usecase/FeedCollectionCommentWriteUseCase.java, be/src/main/java/com/foodymoody/be/feed_collection_comment/presentation/FeedCollectionCommentWriteController.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/application/FeedCollectionReplyReadService.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/application/FeedCollectionReplyWriteService.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/domain/FeedCollectionReplaySummary.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/domain/FeedCollectionReply.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/domain/FeedCollectionReplyRepository.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/persistence/FeedCollectionReplyRepositoryImpl.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/persistence/jpa/FeedCollectionReplyJpaRepository.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/usecase/FeedCollectionReplyMapper.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/usecase/FeedCollectionReplyReadUseCase.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/usecase/FeedCollectionReplyResponse.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/usecase/FeedCollectionReplyWriteUseCase.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/presentation/FeedCollectionReplyReadController.java, be/src/main/java/com/foodymoody/be/feed_collection_reply/presentation/FeedCollectionReplyWriteController.java, be/src/main/resources/application-filter.yml, be/src/test/java/com/foodymoody/be/acceptance/feed_collection_comment/FeedCollectionCommentAcceptanceTest.java, be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply/FeedCollectionReplyAcceptanceTest.java, be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply/FeedCollectionReplySteps.java
- cotent 를 Content 타입을 만들었다
- 다른 create_at 와 같은 객체를 만들고 함께 관리하면 어떨까요 ?
=> [BE] 컬렉션 대댓글 기능
